name: Тест и обновление

on:
    push: 
        branches: [master]

jobs: 
    testing: 
       runs-on: ubuntu-24.04
       env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          DB_ENGINE: ${{ secrets.DB_ENGINE }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DEBUG: ${{ secrets.DEBUG }}
       servises:
         postgresql_main:
           image: postgres:12
           env:
             POSTGRES_DB: ${{ env.DB_NAME }}
             POSTGRES_USER: ${{ env.DB_USER }}
             POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
           port:
             - 5432:5432
           options: 
             --health-cmd pg_isready
             --health-interval 5s
             --health-timeout 5s
             --health-retries 5
        
       steps:
         - name: Проверка изменений
           uses: actions/checkout@v4

         - name: Установка Python
           uses: actions/setup-python@v4
           with:
             - python-version: "3.12"
              
         - name: Установить зависимости
           run: pip install -r -requirements.txt

         - name: Линтинг
           run: flake8 logistic/ --exclude=logistic/migrations/

         - name: Тестирование
           run: python manage.py test
           env:
             SECRET_KEY: ${{ env.SECRET_KEY }}
             ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
             DB_ENGINE: ${{ env.DB_ENGINE }}
             DB_HOST: ${{ env.DB_HOST }}
             DB_NAME: ${{ env.DB_NAME }}
             DB_PASSWORD: ${{ env.DB_PASSWORD }}
             DB_PORT: ${{ env.DB_PORT }}
             DB_USER: ${{ env.DB_USER }}
             DEBUG: ${{ env.DEBUG }}






    
